--Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as revenue
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount)from customer);

-- Q3. Which are the top 5 products with the highest average review rating?

select * from customer;

select item_purchased, round(avg(review_rating::numeric),2) avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select * from customer;

select shipping_type, round(avg(purchase_amount::numeric),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.


select * from customer;

select subscription_status, count(customer_id) as num_of_customers, round(avg(purchase_amount::numeric), 2) as avg_purchase_amount, sum(purchase_amount) as total_revenue
from customer
group by subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select * from customer;

-- Wrong approach,
-- select item_purchased, round(count(*)::numeric * 100.0/ (select count(*) from customer where discount_applied = 'Yes' ),2) as product_percentage
-- from customer
-- group by item_purchased
-- order by product_percentage desc
-- limit 5;

select item_purchased,
	round(sum(case when discount_applied = 'Yes' then 1 else 0 end) * 100.0/count(*),2) discount_percentage
from customer
group by item_purchased
order by discount_percentage desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

select * from customer;

with customer_type as (
select customer_id, previous_purchases, 
case when previous_purchases = 1 then 'New'
	when previous_purchases between 1 and 10 then 'Returning'
	else 'Loyal'
end as customer_segment
from customer
)

select customer_segment, count(*)
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 

select * from customer;

with category_items_ranked as (
select category, item_purchased, count(*) count, rank() over(partition by category order by count(*) desc) rn
from customer
group by category, item_purchased
)

select category, item_purchased, count
from category_items_ranked
where category_items_ranked.rn <= 3
;

-- --Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


select subscription_status, count(customer_id)
from customer
where previous_purchases > 5
group by subscription_status;

--Q10. What is the revenue contribution of each age group? 

select * from customer;

select age_group, sum(purchase_amount)
from customer
group by age_group;

